### ISSUE TITLE
Added later

### ISSUE THREAD

**Issue by msakovic1** [SlimeKnights/TinkersToolLeveling#100]
So I started the Hexxit mod with a friend, after a while I thought I should Add this mod to the modpack to enhance gameplay. After I added it, all new tools get the leveling, but the old ones don't. Is there a way to add the lvling to the already made, pre thinkers' tool leveling mod?

**Comment by bonii-xx** [comment]
Sadly no, the tool leveling aspect is a inherent property of the built tool. Think of it like a trait/modifier added on construction.
