### ISSUE TITLE
Dynamic Trees Integreation

### ISSUE THREAD

**Issue by DAmNRelentless** [SlimeKnights/TinkersToolLeveling#104]
It would be cool if Tinkers Tool Leveling would properly work with dynamic trees.
The hatchet from TConstruct works on the trees flawlessly. Also the right amount of durability is taken from it.
However you only get 1XP because you only break the lowest block. There should be an option that you get XP for the whole tree.

**Comment by bonii-xx** [comment]
That means dynamic trees isn't actually using the hatchet to break the block, but just removes the durability. That's on their side.
