### ISSUE TITLE
Construct's Armory Compatibility?

### ISSUE THREAD

**Issue by zauberparacelsus** [SlimeKnights/TinkersToolLeveling#107]
I am using this mod alongside Construct's Armory, and I've found that although an XP readout is shown on the armors from construct's armory, they do not receive XP.

Is this a breakage in Construct's Armory support, or is it just unsupported and the XP readout isn't supposed to show up on the armors?

**Comment by KnightMiner** [comment]
The XP shows on armor as its a Tinker Tool, but I assume since they never added specific support it will gain XP whenever you hit an enemy while holding the armor. Hard to say which side should add support, but special support will be needed on one side or the other.

**Comment by zauberparacelsus** [comment]
After looking at the FAQ for Construct's Armory, it does have support for Tinker's Tool Leveling:

```
Q. Does this have integration with <insert Tinkers' add-on>?

A. Only Tinkers' Tool Leveling. All other add-ons will have to do integration on their end as I generally only want to include features that are in base Tinkers' Construct.
```

I'll be closing this and filing a separate bug report over there.
