### ISSUE TITLE
[1.12.2] The Faster the bow/crossbow the less XP i get.

### ISSUE THREAD

**Issue by MatthewLimma** [SlimeKnights/TinkersToolLeveling#108]
Tinkers: 1.12-2.13.0.171
Mantle: 1.12-1.3.3.55
T. Tool Leveling: 1.12.2-1.1.0

For some reason my bow is only gaining 1 XP per kill the bow is made of Plastic, Dragon Bones, Regular String, and paper, the bow + arrow is a hit kill weapon to a standard 20 hp character but for some reason it only gain 1 xp per kill, to test this i made a full Dragon Bone bow witch is gaining 13~14 XP per kill but has a much longer draw speed.

The first image is the "fast" bow that only gain 1xp 
The second is the slow bow that gain regular XP

![Screenshot_4](https://user-images.githubusercontent.com/53840604/74120018-a008c000-4ba0-11ea-8d5d-3f453c655386.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/53840604/74120020-a1d28380-4ba0-11ea-982f-c05ff64e0156.jpg)

**Comment by bonii-xx** [comment]
Yes, bows get xp for shooting things, but not the damage dealt (the arrows get that). To balance out bows they get xp relative to their drawspeed.

**Comment by MatthewLimma** [comment]
Is there a way for me to add more xp gain?  Or tweaking the mod script will be necessary ?

**Comment by bonii-xx** [comment]
Having it fire 1 arrow per second is probably optimal for leveling.. other than that you can always change the configs for it to require less xp.
