### ISSUE TITLE
Whats the Maximum level for the tools?

### ISSUE THREAD

**Issue by Lion4K** [SlimeKnights/TinkersToolLeveling#11]
My pickaxe is level Heroic already

**Comment by bonii-xx** [comment]
Currently none. Default will stay none.

**Comment by Lion4K** [comment]
I mean, it gotta run out of names, Legendary already.

**Comment by akanimh** [comment]
I had the same question, opened up the language file in the mod to see:

`tooltip.level.0=Like new
tooltip.level.1=Clumsy
tooltip.level.2=Comfortable
tooltip.level.3=Accustomed
tooltip.level.4=Adept
tooltip.level.5=Expert
tooltip.level.6=Master
tooltip.level.7=Grandmaster
tooltip.level.8=Heroic
tooltip.level.9=Legendary
tooltip.level.10=Godlike
tooltip.level.11=Awesome
tooltip.level.19=MoxieGrrl
tooltip.level.42=boni
tooltip.level.66=Jadedcat
tooltip.level.99=Hacker`
