### ISSUE TITLE
I want deactivate vanilla tools like in "Iguana Tweaks for Tinkers Construct"

### ISSUE THREAD

**Issue by Silverseppel** [SlimeKnights/TinkersToolLeveling#110]
Hi
I want deactivate vanilla tools like in "Iguana Tweaks for Tinkers Construct"
Can you implement it. With "Iguana Tweaks for Tinkers Construct" vanilla tools can only be used for recipes not for mining and so on

**Comment by KnightMiner** [comment]
This already exists in another mod. Look into Tinkers Hegemony. Tinkers Survival also adds the feature, but I have less experience with that mod.

**Comment by bonii-xx** [comment]
Disabling vanilla tools is not part of this mod, and wont be.
