### ISSUE TITLE
Shurikens don't level when fired from mechanical users

### ISSUE THREAD

**Issue by panenw** [SlimeKnights/TinkersToolLeveling#113]
Shurikens don't level when fired from mechanical users (Exu2, 1.12.2), unlike cleavers (when i tested).
How to reproduce:
1) Make shuriken (I used reinforced pink/paper/wood/manullyn)
2) put in mechanical user set to right click
3) have it kill a zombie
4) check exp

**Comment by bonii-xx** [comment]
The fake player might not be registered with the world, which breaks player tracking. Anyway, this is not something that's supported by design, more by happenstance.
