### ISSUE TITLE
Default Experience on Tools is WAY TOO High!

### ISSUE THREAD

**Issue by DizzyDJW** [SlimeKnights/TinkersToolLeveling#115]
The default in the configs is set to 20,000! Which would require 20,000 blocks to be mined to gain a SINGLE level on the tool, (not to mention the minimum multiplier is 2x, meaning each additional level is DOUBLE as much XP required), was this a typo as a few of the tools are set to "2000" and "2500" respectively?

Also, can you make the configs adjustable on the fly or at the very least compatible with the "/relaodConfigs" command?

Having to wait 8-12mins after restarting the entire client, just to change some small values, isn't right.

**Comment by KnightMiner** [comment]
Default base XP is 500 per [this line of code](https://github.com/SlimeKnights/TinkersToolLeveling/blob/master/src/main/java/slimeknights/toolleveling/config/ConfigFile.java#L83), you sure you are seeing 20000, and you did not set that value yourself/your modpack maker set it?

As for a config reload command, once you have the config set up you will not need to reload anymore, will you? Pretty sure there is no forge reload config command by default, some mod is likely adding that for you.
