### ISSUE TITLE
update to 1.16.5

### ISSUE THREAD

**Issue by andylmfao** [SlimeKnights/TinkersToolLeveling#124]
pleassee, we all want a new version :( it's no fun playing without

**Comment by Insane96** [comment]
Actually is a lot of fun playing the new TiCon 3 without Tool Leveling

**Comment by andylmfao** [comment]
i tried on the older versions, but It's just no-where near as fun to have restrictions like that in a sandbox game.

**Comment by ShinyPorygon** [comment]
![Screenshot_20210904-123101](https://user-images.githubusercontent.com/35193007/132101734-d6090545-6c74-4c76-89ac-b793861f2363.png)

**Comment by Insane96** [comment]
Restrictions? More like balance.

**Comment by KnightMiner** [comment]
Don't ask for updates. You are free to update the mod yourself

**Comment by andylmfao** [comment]
> Restrictions? More like balance.

It's minecraft. It's a sandbox game.

**Comment by KnightMiner** [comment]
It's a sandbox game, which means we are free to play the game as we want and code what we want. If you want to play the game as you want (leveling) you have to either code leveling yourself or find someone else who agrees that is how the sandbox should be played. The argument that it's a sandbox game so we should write you a mod is dumb

**Comment by andylmfao** [comment]
I never said you should or have to do anything, It was merely a suggestion, sorry if it didn't come across as that.
