### ISSUE TITLE
[Suggestion] Modifier Remover/Scrubber

### ISSUE THREAD

**Issue by MokahTGS** [SlimeKnights/TinkersToolLeveling#13]
I'm wondering if you could add a way to remove a modifier from a tool after it gains it.  This would be useful if you get a modifier that you don't want on a particular tool.  eg. Autosmelt on a pickaxe can be very annoying...being able to remove the last added modifier would be nice.

**Comment by KnightMiner** [comment]
Autosmelt is a material and thus cannot be applied randomly, perhaps you mean silky or another similar one.

In any case, last I checked there are no random modifiers applied, just a modifier slot opened so you may choose one yourself

**Comment by MokahTGS** [comment]
Ah...that is different than it used to work (better IMO).  Great.
