### ISSUE TITLE
Crash while tool levels up in Progressive Automation machine (chopper)

### ISSUE THREAD

**Issue by SPMoo66** [SlimeKnights/TinkersToolLeveling#15]
When the tool inside the chopper leveled up, our server crashed. We're still on [0.2.0], so if that's the problem, I apologize.

http://pastebin.com/gAYhiknf

Sorry if this is a Progressive Automation issue, I'll link it over to them if it is.

**Comment by bonii-xx** [comment]
Update Tic

**Comment by SPMoo66** [comment]
Ok, thanks for the help!
