### ISSUE TITLE
no modifiers on tool leveling up (FTB Infinity)

### ISSUE THREAD

**Issue by Too-DAMN-Much** [SlimeKnights/TinkersToolLeveling#16]
not getting any modifiers applied on tool level up, unsure why, checked config, didn't see anything to disable it.

version TinkerToolLeveling-1.10.2-1.0.1

**Comment by bonii-xx** [comment]
Because you're getting free modifiers.

**Comment by Too-DAMN-Much** [comment]
that's only half of what should be happening on level up? should have a modifier slot added AND filled randomly.

**Comment by bonii-xx** [comment]
Does it say so anywhere?

**Comment by Too-DAMN-Much** [comment]
the description, obviously.

might be a good idea to explain that this is just a worthless stealth-nerf otherwise, modifier slots are already next to free anyway.

**Comment by bonii-xx** [comment]
>On levelup an extra modifier is rewarded.

**Comment by Too-DAMN-Much** [comment]
that's not what i'm seeing ingame, only a space for a modifier, not an actual modifier being applied.

**Comment by Ravin890** [comment]
Dude it only gives extra modifier slots, not modifiers

**Comment by Too-DAMN-Much** [comment]
quite deceptively worded in that case, also extremely pointless.

**Comment by Ravin890** [comment]
How is it pointless? You can add whatever modifiers you want with extra slots.

**Comment by Too-DAMN-Much** [comment]
besides the obvious way?

extra modifiers slots are easily gotten, make it with a paper part, thaumium, use a few gold and diamonds, it's not really worthwhile to use this mod.

**Comment by Ravin890** [comment]
Have you played with tinkers 1.10?

**Comment by Too-DAMN-Much** [comment]
that is the current version, yes.

**Comment by Ravin890** [comment]
Only reason i ask is that thaumium isn't even in game due to thaumcraft not being available (unless you are anazor's patreon or an official addon creator for thaumcraft) and i thought that the diamond + gold modifier thing was removed (unless it was added back in without me noticing)

**Comment by Too-DAMN-Much** [comment]
fair enough on thaumium but i just started investigating whether 1.10 version was any point to playing and hadn't bothered to check if thaumcraft was updated yet, from what i read the diamond and gold modifier was recently patched back in.

either way, it's not like free slots for modifiers were a worthwhile reward ever, just use paper.

furthermore, they're certainly not progression.

finally, a lot of the modifiers are just plain trash in this version as well as far too expensive, i've applied mossy to all of my tools and made a note of the durability not a single one has healed even one point from mossy rank 3 which now costs 10 levels for absolutely no reason.
