### ISSUE TITLE
Capability conflict between SpecialAI and TinkersToolLeveling

### ISSUE THREAD

**Issue by McJty** [SlimeKnights/TinkersToolLeveling#18]
With SpecialAI (special_ai-1.10.2-1.1.3.jar) and TinkersToolLeveling (TinkerToolLeveling-1.10.2-1.0.1.jar) installed I often get this crash in the log (it doesn't actually crash the game):

https://bpaste.net/show/c804a5a1cf3d

**Comment by bonii-xx** [comment]
Cleanup, closing old tickets. Also RIP paste
