### ISSUE TITLE
[1.10.2 - 1.0.1] Bows don't level up unless you hit enemies with them in melee

### ISSUE THREAD

**Issue by VallenFrostweaver** [SlimeKnights/TinkersToolLeveling#19]
As the title states. Bows don't level up unless used as a melee weapon.

**Comment by RealGrep** [comment]
Just evaluating this for the pack, and I noticed this. Seems really silly to only be able to get the new modifiers from levelling your bow by literally hitting things over the head with it. Hopefully that can be addressed. :)

**Comment by OtterofDeath** [comment]
I am also having this issue. Currently getting around this by lowering the XP requirement in the config file. Which is far from perfect, but it kinda works.

**Comment by JonoColwell** [comment]
Issue still occurring.

**Comment by Jomik** [comment]
Happens in 1.11.2 too.
#38

**Comment by InjuredWolf** [comment]
The general gist of issue: XP is only given to whatever it is that deals the damage to the mob. Since a bow never actually does that unless you whack the mob with the bow itself, the bow therefore does not receive XP.

**Comment by InjuredWolf** [comment]
Could something be done using the bonus damage that bows sometimes give?

**Comment by Jomik** [comment]
I was thinking to add a check, if the damage dealing item is a bolt/arrow, then split the exp between the bow/crossbow and the arrow/bolt.

**Comment by Angelin01** [comment]
Since this wasn't posted here, there is an addon for 1.10 called [Tinkers Tool Leveling Addon for Bows](https://minecraft.curseforge.com/projects/tinkers-tool-leveling-addon-for-bows) that fixes this.  

Sadly, no other versions that I know of.

**Comment by xenoflot** [comment]
An interesting addition to this issue... I just shot a blaze and my Longsword got the XP.

**Comment by Zsashas** [comment]
Any solution to this yet?

**Comment by Jomik** [comment]
Latest update sounds like it fixes this?
in https://github.com/SlimeKnights/TinkersToolLeveling/commit/f76ed27ec434ea72493d1e115396246f00500126, or is it different @bonii-xx ?

**Comment by bonii-xx** [comment]
Fixed in newest version
