### ISSUE TITLE
Crash On start up

### ISSUE THREAD

**Issue by mightydanp** [SlimeKnights/TinkersToolLeveling#2]
When i add this to my mods folder and launch it it crashes with this.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  CCCDeobfPlugin (unknown)
  IC2core (industrialcraft-2-2.6.66-ex110.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.78-universal.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.1.147-universal.jar)
  GregtechASM (gregtech-5.09.22.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.54-beta.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal (1).jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 9/13/16 9:33 AM
Description: Rendering screen

java.lang.NoClassDefFoundError: bxl
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: net.minecraftforge.fml.client.GuiModsMissing
	Mouse location: Scaled: (0, 239). Absolute: (0, 0)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 209363288 bytes (199 MB) / 514244608 bytes (490 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2080 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2080.jar) 
	U	Forge{12.18.1.2080} [Minecraft Forge] (forge-1.10.2-12.18.1.2080.jar) 
	U	CodeChickenCore{2.1.8.79} [CodeChicken Core] (minecraft.jar) 
	U	NotEnoughItems{2.1.1.147} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.1.147-universal.jar) 
	U	OpenComputers|Core{1.6.0.3-rc.1} [OpenComputers (Core)] (minecraft.jar) 
	U	AppleCore{2.0.1} [AppleCore] (AppleCore-mc1.10.2-2.0.1.jar) 
	U	babymobs{1.5} [Baby Mobs] (BabyMobs-1.10.2-1.5.jar) 
	U	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	U	bdlib{1.12.2.8} [BD Lib] (bdlib-1.12.2.8-mc1.10.2.jar) 
	U	Botania{r1.8-321} [Botania] (Botania-unofficial.r1.8-321.jar) 
	U	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	U	commoncapabilities{1.1.2} [CommonCapabilities] (CommonCapabilities-1.9.4-1.1.2.jar) 
	U	CompactSolars{5.0.4.328} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.4.328-universal.jar) 
	U	craftingtweaks{6.1.12} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.12.jar) 
	U	MineTweaker3{3.0.11} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.11.jar) 
	U	cyclopscore{0.7.7} [Cyclops Core] (CyclopsCore-1.9.4-0.7.7.jar) 
	U	endercore{1.10.2-0.4.1.54-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.54-beta.jar) 
	U	EnderIO{1.10.2-3.0.1.107_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.107_beta.jar) 
	U	FFS{1.9.4-1.6.4-b28} [Fancy Fluid Storage] (Fancy Fluid Storage-1.9.4-1.6.4-b28.jar) 
	U	gregtech{MC1710} [GregTech] (gregtech-5.09.22.jar) 
	U	hardcorewither{2.0.0} [Hardcore Wither] (hardcoreWither-1.10.2-2.0.0-alpha2-27-universal.jar) 
	U	IC2{2.6.66-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.66-ex110.jar) 
	U	JEI{3.9.3.252} [Just Enough Items] (jei_1.10.2-3.9.3.252.jar) 
	U	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	U	fyberbackpack{1.0.2} [Just Backpacks] (justbackpacks-mc1.9.4-1.0.2.jar) 
	U	jeresources{0.4.8.48} [Just Enough Resources] (JustEnoughResources-1.10.2-0.4.8.48.jar) 
	U	mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
	U	modtweaker{2.0.2} [Mod Tweaker] (ModTweaker2-2.0.2.jar) 
	U	OpenComputers{1.6.0.3-rc.1} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar) 
	U	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2b.jar) 
	U	pressure{1.3.1.13} [Pressure Pipes] (pressure-1.3.1.13-mc1.10.2.jar) 
	U	randomthings{3.7.5} [Random Things] (RandomThings-MC1.10.2-3.7.5.jar) 
	U	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	U	RTG{1.10.2} [Realistic Terrain Generation] (RTG-1.10.2-4.1.1.2-snapshot-4.jar) 
	U	StorageDrawers{1.10.2-3.2.7} [Storage Drawers] (StorageDrawers-1.10.2-3.2.7.jar) 
	U	tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
	U	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	U	tinkertoolleveling{1.10.2-0.1.0.DEV.b5240c7} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-0.1.0.jar) 
	U	ToughAsNails{1.0.11} [Tough As Nails] (ToughAsNails-1.9.4-1.0.11.jar) 
	U	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	U	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.203.jar) 
	U	wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.203.jar) 
	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
CCCDeobfPlugin (unknown)
  
IC2core (industrialcraft-2-2.6.66-ex110.jar)
  
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.78-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  lumien.randomthings.asm.ClassTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.1.147-universal.jar)
  codechicken.nei.asm.NEITransformer
GregtechASM (gregtech-5.09.22.jar)
  gregtech.asm.ASM
EnderCorePlugin (EnderCore-1.10.2-0.4.1.54-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal (1).jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.70' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Launched Version: 1.10.2-forge1.10.2-12.18.1.2080
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.70, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-5500 APU with Radeon(tm) HD Graphics

**Comment by bonii-xx** [comment]
You need TiC 2.5.0 or higher. Also one of your mods breaks the dependency error screen.

**Comment by mightydanp** [comment]
Dependency error screen?

**Comment by bonii-xx** [comment]
The one that'd tell you that you need TiC 2.5.0
