### ISSUE TITLE
Suggestion: XP Requirement modifier

### ISSUE THREAD

**Issue by Martijnpold** [SlimeKnights/TinkersToolLeveling#21]
Right now the mod will double the XP Requirement for every single level that is gained on a tool. What I would extremely love to see is an ability to change that. For instance: When a user enters 1.05 in the config the level requirement will go up by 5% for every gained level (ex: level 1 requires 500 xp, level 2 requires 525, level 3 requires 551 xp). This would allow for much greater customization and would allow servers to make levelling less or more grindy.

Hope it gets added :)

**Comment by Nacoran** [comment]
Doh!  I think I submitted a similar idea.  A lot of XP tables in games use something like the fibonacci sequence.
