### ISSUE TITLE
Mattock doesn't get xp when used on Bimoes'o'plenty blocks

### ISSUE THREAD

**Issue by Erfurt92** [SlimeKnights/TinkersToolLeveling#22]
Hey, I have noticed that whenever I use the mattock, as a hoe, on different dirt/grass blocks from Biome'o'plenty, it seems that they don't get any xp.

I'm not sure, if this is the only thing, or if it's a general compatibility issue between the two mods.

**Comment by bonii-xx** [comment]
Mattocks only call the vanilla implementation. Sounds like BoP is returning the wrong result on the event.

**Comment by bonii-xx** [comment]
Cleanup, closing old tickets.
