### ISSUE TITLE
Unable to change XP needed for leveling 

### ISSUE THREAD

**Issue by ThisNThat01** [SlimeKnights/TinkersToolLeveling#24]
I have this mod installed on my modpack and even after changing the xp levels in the config and making a new singleplayer world all the XP levels were still what they were originally set to

**Comment by bonii-xx** [comment]
Which version of the mod?

**Comment by biohazard457** [comment]
I am having the same issue. I am using 1.10.2-1.0.1

**Comment by ThisNThat01** [comment]
im also using 1.10.2-1.0.1

**Comment by superdave4054** [comment]
Also having the same issue. Changed the default 500 xp to 300, saved the file. No change in game. Same version as well 1.10.2-1.0.1

**Comment by bonii-xx** [comment]
Cleanup, closing old tickets.
