### ISSUE TITLE
[Suggestion] Add an option for increasing required EXP based on reinforcement modifiers

### ISSUE THREAD

**Issue by starg09** [SlimeKnights/TinkersToolLeveling#25]
Currently you can build unbreakable tools by having two paper pieces, then adding 5 "Reinforcement" modifiers. Having TiToLe in a pack, this means you could automate the tools' usage in some way (Main possibility being a Mechanical User from ExU2), and let it level up in a matter of minutes. Then you could apply speed, fortune/silk, and with a high-level sharpening kit you could get a pretty OP tool in pretty early game.

My suggestion: Making it so when you add a modifier to a tool for increasing their durability, the base required EXP for that particular tool increases accordingly. In the case of making a tool unbreakable, the tool can no longer be leveled up at all (not even current level).

This could, of course, be toggled off in the config, but would help improving the balance of this mechanic in certain packs...

Two modifiers that could be affected for this:

* Reinforcement: Every 20% reinforced increases base required EXP in 30% (Increase considers previous augments, so Reinforced would be 130%, Reinforced II would be 169%, and so on...). Reinforced V (Unbreakable) would disable leveling that tool entirely.
* Width++/Height++: Increases mined blocks in a 66% each, but doubles the required EXP for leveling up the tool.

**Comment by bonii-xx** [comment]
The mod in itself is balanced around the XP required. Modpack balance is the modpacks responsibility. Also if you want balance, you shouldn't use Tinkers Tool Leveling. As the mod description states, it's effectively a cheat code.
