### ISSUE TITLE
Server crash?

### ISSUE THREAD

**Issue by Howbowda** [SlimeKnights/TinkersToolLeveling#27]
Adding this mod to the server (Multiplayer) Made it crash on startup, but running the same map (From our multiplayer) In our single player works just fine with the mod. But when the server crashes, it doesn't really show the server crashing in the logs?

**Comment by Howbowda** [comment]
NOTE The mod was being added to our server, which currently has Direwolf 20 modpack, as well as Pixelmon, Hammer core, and Solar flux reborn.

**Comment by bonii-xx** [comment]
Cleanup, closing old tickets.
