### ISSUE TITLE
Setting ToolXP.levelMultiplier in config doesn't change anything

### ISSUE THREAD

**Issue by Sertion** [SlimeKnights/TinkersToolLeveling#29]
Setting `toolxp.levelMultiplier` to anything doesn't change anything in game. It also isn't part of the generated config.

Does it have anything to do with it being a float?

Forge Version: `1.20.2-forge1.10.2-12.18.2221`
Mantle Version: `1.10.2-1.1.5`
Tinker's Construct Version: `1.10.2-2.6.2`
Tinker's Tool Leveling Version: `1.10.2-1.0.1`

**Comment by bonii-xx** [comment]
Oh I must've forgotten to answer/close this, probably d ue to having this conversation way too often, sorry. The config is not exposed in the config, nor will it be, hence why it does nothing/isn't generated. *cleanup*
