### ISSUE TITLE
XP for blocking with signs

### ISSUE THREAD

**Issue by Yowesephth** [SlimeKnights/TinkersToolLeveling#3]
I find signs to make great shield replacements while using a broadsword as a weapon. However, you get no XP for using a battlesign this way.

Would it be possible to add an xp gain for successfully stopping/reflecting damage when blocking (potentially at a reduced rate if balancing is a concern)?

**Comment by bonii-xx** [comment]
Sounds like an idea

**Comment by bonii-xx** [comment]
In the next version
