### ISSUE TITLE
Customized EXP rate for level up

### ISSUE THREAD

**Issue by kyonkonyan** [SlimeKnights/TinkersToolLeveling#34]
Allow users to change EXP modifier by  editing files which related to EXP.

For example,we could use 500/750/1125/1687/2531 to replace original one(which might be 500/1000/2000/4000/8000). The rate has been changed from 200% to 150%.

The default rate (200%) may cause users put most of their time on getting EXP.

**Comment by zimer5500** [comment]
como eu configuro o mod

**Comment by zimer5500** [comment]
How do i set the mod

**Comment by Hexus-One** [comment]
Yes! I'd love to be able to change the XP scaling amount - maybe even have different scalings (linear, exponential like it is currently, logarithmic) available. Even different scaling per tool?

**Comment by Hexus-One** [comment]
Okay I've dug around a bit, found [TinkersToolLeveling/src/main/java/slimeknights/toolleveling/config/ConfigFile.java](https://github.com/SlimeKnights/TinkersToolLeveling/blob/9ff478c364c5f5f2f97c934c8ba3b8ef3f28ec01/src/main/java/slimeknights/toolleveling/config/ConfigFile.java#L88). Could the value in line 88 be made available to adjust in the config? Not sure exactly how it works but it seems to be a very simple change.

**Comment by kyonkonyan** [comment]
@Hexus-One  and Allow unlimited levels ,please

**Comment by Hexus-One** [comment]
Oh? I thought the config file already allowed you to set an upper limit (0 or less for infinite) for levelling.

**Comment by kyonkonyan** [comment]
@Hexus-One oh ...sorry my mistaken..

**Comment by Hexus-One** [comment]
Haha no worries :)

**Comment by kyonkonyan** [comment]
@Hexus-One get exp point for different block ,For example: 1 point for stone ,2 point for iron ore and 4 point for gold ore .can you achieve it? oh and Customized exp getting rate :)

**Comment by bonii-xx** [comment]
The values are not exposed because they act as the soft-cap for amount of modifiers you get.

**Comment by Hexus-One** [comment]
Oh... but surely it would not hurt to make it adjustable to the end users'/modpack creators' discretion? Or would this cause too many additional problems?

**Comment by Hexus-One** [comment]
Edit: may I compile a separate fork for provate use?

**Comment by bonii-xx** [comment]
You can do whatever you want for private use. ;)
