### ISSUE TITLE
NewToolMinModifiers cannot be turned off

### ISSUE THREAD

**Issue by kkjdroid** [SlimeKnights/TinkersToolLeveling#37]
Setting the value arbitrarily high (I used 65535) gives all tools a very large number of modifiers (65532 in my case, not sure why the difference). Setting it to -1 just takes away all modifiers. I'd like to be able to use this mod without rendering paper, magical wood, and enchanted metal pointless.

**Comment by bonii-xx** [comment]
That's not how it works at all. Wrong mod?

**Comment by kkjdroid** [comment]
It definitely does that on my instance. It might be an interaction with Moar Tinkers, though.

**Comment by bonii-xx** [comment]
The config by itself only affects how many modifiers a newly built tool WITHOUT traits/modifiers has at most. So anything >=3 has no impact at all with only regular tinkers tools.

**Comment by zimer5500** [comment]
como eu faço para configurar este mod

**Comment by zimer5500** [comment]
How do i set the mod

**Comment by bonii-xx** [comment]
@kkjdroid I assume I can close this?
