### ISSUE TITLE
Adjustable EXP Rates

### ISSUE THREAD

**Issue by Lytearro** [SlimeKnights/TinkersToolLeveling#39]
It would be nice to see a way to customize or add different amounts of experience to be earned depending on what you're mining. Presently (on my server.) you get 1 experience whether it's Stone, Cobblestone, Redstone, Diamonds, or any other ore introduced through mods. Even though you can upgrade the mining capabilities of your pickaxe, you still don't get any better experience for being able to mine the higher tiers of ores. If there is a way to use a text file or something to load by line each different ore, then all you would need to do is provide a sample of what it should look like per line, then it's up to the server owner to add whichever ore's and custom experience they want.

example:
```text
minecraft:stone 1, 
minecraft:coal_ore 3, 
minecraft:diamond_ore 10,
```

it would be `mod:item_name experience,`

**Comment by bonii-xx** [comment]
Why would a higher level pick get more xp for doing the same thing as a lower level pick, just because the lower level pick can't mine the block? Doesn't make sense.
