### ISSUE TITLE
Custom set values keep resetting

### ISSUE THREAD

**Issue by scalda** [SlimeKnights/TinkersToolLeveling#4]
Hi @bonii-xx 

I am haveing my custom set values reset everytime i load the mod up? 

Is there something i'm doing wrong?

Here's a link to what i want: http://pastebin.com/rHW3EcW8

Regards

Scalda

**Comment by terrinkern** [comment]
I'm having the same issue. I'm using higher values but none of them are staying. Every reload everything is back to 500 and 4500.

Thanks 
Terrin

**Comment by Zeevian** [comment]
I personally managed to get them to save, somehow.  I think editing and spamming save? Anyhow, even though it hasn't changed back to the default, it isn't saving in game.  It still requires 500/4500 to level them up.

**Comment by bonii-xx** [comment]
Fixed in 0.2.0
