### ISSUE TITLE
Crash on Server but not on SSP vs TinkerToolLeveling-1.12-1.0.2

### ISSUE THREAD

**Issue by Tomatoh** [SlimeKnights/TinkersToolLeveling#45]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinkers Tool Leveling (tinkertoolleveling)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag

**Comment by Mohron** [comment]
same issue

**Comment by EmosewaGamer** [comment]
The full crash: https://pastebin.com/eHAZE1z9

**Comment by bonii-xx** [comment]
Hm, I was pretty sure I changed the part that caused this in the update.. Maybe there's more than one. Thanks for reporting.
