### ISSUE TITLE
[1.12.2] Tinker Tool Leveling 1.12-1.0.2b works, but is not marked as such on Curse

### ISSUE THREAD

**Issue by sandalle** [SlimeKnights/TinkersToolLeveling#50]
[Tinker Tool Leveling 1.12-1.0.2b](https://minecraft.curseforge.com/projects/tinkers-tool-leveling/files/2474358) works (Forge Mod Loader 14.23.0.2515), but is not marked as such on Curse disallowing modpacks from using it.

**Comment by bonii-xx** [comment]
Right, thanks, forgot to update that. Done!
