### ISSUE TITLE
Changing Tool XP required for specific items

### ISSUE THREAD

**Issue by JungleSnake** [SlimeKnights/TinkersToolLeveling#53]
**Minecraft version:** `1.12`
**Tinkers Tool Leveling version:** `1.12-1.0.2b (1.12-1.0.2b.DEV.1a79301)`
**Tinkers' Construct version:** `1.12-2.7.4.34`
**Forge Mod Loader version:** `8.0.99.99`
**Minecraft Forge version:** `14.23.0.2531`
**Specific Mod Pack:** `Direwolf20 1.12`

**Log:** There is only one mention of Tinkers Tool Leveling in the start up log, and was only for the Resource Manager listing all the mods its found

**Problem:** When I go into the config file to set xp requirements for certain tools, it does not use the number for that tool stated in the config file.

**my config file:**
```
"_VERSION"=1
general {
    # Maximum achievable levels. If set to 0 or lower there is no upper limit
    maximumLevels=-1
    # Reduces the amount of modifiers a newly build tool gets if the value is lower than the regular amount of modifiers the tool would have
    newToolMinModifiers=3
}
toolxp {
    # Base XP for each of the listed tools
    baseXpForTool {
        "tconstruct:arrow"=500
        "tconstruct:battlesign"=500
        "tconstruct:bolt"=500
        "tconstruct:broadsword"=500
        "tconstruct:cleaver"=500
        "tconstruct:crossbow"=500
        "tconstruct:excavator"=4500
        "tconstruct:frypan"=500
        "tconstruct:hammer"=4500
        "tconstruct:hatchet"=500
        "tconstruct:longbow"=500
        "tconstruct:longsword"=500
        "tconstruct:lumberaxe"=4500
        "tconstruct:mattock"=500
        "tconstruct:pickaxe"=500
        "tconstruct:rapier"=500
        "tconstruct:scythe"=4500
        "tconstruct:shortbow"=500
        "tconstruct:shovel"=500
        "tconstruct:shuriken"=500
    }
    # Base XP used when no more specific entry is present for the tool
    defaultBaseXP=500
}
```

Any help will be gladly appreciated, thank you for your time.

### Edit1: The above config file does work for defaultBaseXP=500, I can change this 500 to any number and that number is correctly reflected in the game, however, the baseXpForTool is still not using the numbers I stated.

**Comment by bonii-xx** [comment]
Fixed in newest version

**Comment by JungleSnake** [comment]
Thank you so much for your time and hard work! I enjoy this mod!
