### ISSUE TITLE
Does not work for bows and crossbows

### ISSUE THREAD

**Issue by D3nnis3n** [SlimeKnights/TinkersToolLeveling#54]
Hello, i updated TiC and this mod yesterday. (TinkerToolLeveling-1.12-1.0.3.jar)
The changelog says:
"Bows and Crossbows now also get XP for hitting stuff with them."

This is not the case. Bows and crossbows have no Information for xp on them at all.

**Comment by bonii-xx** [comment]
Try reproducing with only TTL, TiC, Mantle and Forge version. Lastest versions.

**Comment by D3nnis3n** [comment]
No need, i do that regulary before reporting issues - issue persists.

**Comment by bonii-xx** [comment]
Hold f3 and C for 10 seconds, and post the crashlog please.

**Comment by D3nnis3n** [comment]
Here you go:

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
> Contact their authors BEFORE contacting forge
> 
> // I just don't know what went wrong :(
> 
> Time: 12/10/17 3:40 PM
> Description: Manually triggered debug crash
> 
> java.lang.Throwable
> 	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1923)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1923)
> 
> -- Affected level --
> Details:
> 	Level name: MpServer
> 	All players: 1 total; [EntityPlayerSP['D3nnis3n'/1914, l='MpServer', x=220.56, y=72.76, z=242.36]]
> 	Chunk stats: MultiplayerChunkCache: 279, 279
> 	Level seed: 0
> 	Level generator: ID 00 - default, ver 1. Features enabled: false
> 	Level generator options: 
> 	Level spawn location: World: (204,64,256), Chunk: (at 12,4,0 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Level time: 1368 game time, 1368 day time
> 	Level dimension: 0
> 	Level storage version: 0x00000 - Unknown?
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
> 	Forced entities: 80 total; [EntityParrot['Parrot'/7, l='MpServer', x=147.25, y=69.10, z=238.53], EntityParrot['Parrot'/8, l='MpServer', x=146.75, y=72.00, z=241.25], EntityPig['Pig'/9, l='MpServer', x=143.50, y=68.00, z=238.50], EntityBat['Bat'/2059, l='MpServer', x=211.56, y=55.22, z=311.25], EntityBat['Bat'/2060, l='MpServer', x=203.44, y=58.95, z=305.58], EntityPig['Pig'/14, l='MpServer', x=167.50, y=81.00, z=207.50], EntityPig['Pig'/15, l='MpServer', x=167.50, y=81.00, z=207.50], EntityPig['Pig'/16, l='MpServer', x=167.50, y=79.00, z=213.97], EntityPig['Pig'/17, l='MpServer', x=188.50, y=75.00, z=208.50], EntityPig['Pig'/18, l='MpServer', x=186.50, y=76.00, z=211.50], EntityPig['Pig'/19, l='MpServer', x=186.50, y=76.00, z=213.50], EntityPig['Pig'/20, l='MpServer', x=186.50, y=76.00, z=214.50], EntityPig['Pig'/28, l='MpServer', x=219.41, y=65.00, z=249.47], EntitySkeleton['Skeleton'/2591, l='MpServer', x=201.50, y=55.00, z=307.50], EntitySkeleton['Skeleton'/2592, l='MpServer', x=201.50, y=55.00, z=306.50], EntityPig['Pig'/33, l='MpServer', x=251.72, y=68.00, z=280.84], EntityCreeper['Creeper'/2594, l='MpServer', x=207.50, y=55.00, z=301.50], EntityCreeper['Creeper'/2595, l='MpServer', x=208.50, y=55.00, z=306.50], EntityPig['Pig'/38, l='MpServer', x=251.50, y=66.00, z=169.50], EntityPig['Pig'/39, l='MpServer', x=249.50, y=66.00, z=173.50], EntityPig['Pig'/40, l='MpServer', x=255.50, y=65.00, z=178.50], EntitySheep['Sheep'/41, l='MpServer', x=258.50, y=64.00, z=219.50], EntitySheep['Sheep'/42, l='MpServer', x=262.50, y=63.00, z=219.50], EntitySheep['Sheep'/43, l='MpServer', x=261.50, y=63.00, z=219.50], EntitySheep['Sheep'/44, l='MpServer', x=269.27, y=65.00, z=211.54], EntityPig['Pig'/48, l='MpServer', x=276.02, y=63.00, z=288.62], EntityPig['Pig'/49, l='MpServer', x=275.50, y=63.00, z=287.01], EntitySkeleton['Skeleton'/2609, l='MpServer', x=231.50, y=59.00, z=178.50], EntityPig['Pig'/50, l='MpServer', x=276.50, y=63.00, z=286.50], EntitySpider['Spider'/2357, l='MpServer', x=257.69, y=47.00, z=209.97], EntityCreeper['Creeper'/2362, l='MpServer', x=254.50, y=45.00, z=207.50], EntityBat['Bat'/2622, l='MpServer', x=240.81, y=15.07, z=211.19], EntitySkeleton['Skeleton'/2369, l='MpServer', x=192.50, y=17.00, z=314.50], EntityZombie['Zombie'/2114, l='MpServer', x=243.50, y=42.00, z=302.50], EntityCreeper['Creeper'/2633, l='MpServer', x=245.50, y=47.00, z=185.50], EntityCreeper['Creeper'/2634, l='MpServer', x=249.50, y=47.00, z=187.50], EntityCreeper['Creeper'/2649, l='MpServer', x=150.50, y=25.00, z=231.50], EntityCreeper['Creeper'/2395, l='MpServer', x=253.50, y=42.00, z=308.50], EntitySkeleton['Skeleton'/2651, l='MpServer', x=150.50, y=25.00, z=230.50], EntityCreeper['Creeper'/2396, l='MpServer', x=251.50, y=42.00, z=309.50], EntityBat['Bat'/2142, l='MpServer', x=158.82, y=52.21, z=247.91], EntityBat['Bat'/2143, l='MpServer', x=156.08, y=55.80, z=249.42], EntityItem['item.item.porkchopRaw'/2655, l='MpServer', x=223.88, y=65.00, z=255.13], EntityBat['Bat'/2169, l='MpServer', x=229.47, y=49.19, z=311.38], EntityBat['Bat'/2173, l='MpServer', x=227.69, y=48.31, z=311.28], EntityPlayerSP['D3nnis3n'/1914, l='MpServer', x=220.56, y=72.76, z=242.36], EntitySkeleton['Skeleton'/2697, l='MpServer', x=231.81, y=46.00, z=292.70], EntityCreeper['Creeper'/2699, l='MpServer', x=228.50, y=44.00, z=266.50], EntitySkeleton['Skeleton'/2700, l='MpServer', x=224.52, y=45.00, z=275.29], EntitySkeleton['Skeleton'/2701, l='MpServer', x=223.78, y=44.00, z=271.49], EntitySkeleton['Skeleton'/2702, l='MpServer', x=224.10, y=44.00, z=273.44], EntityZombie['Zombie'/2450, l='MpServer', x=150.50, y=36.00, z=227.50], EntityCreeper['Creeper'/2712, l='MpServer', x=252.83, y=47.00, z=278.51], EntityCreeper['Creeper'/2466, l='MpServer', x=253.50, y=45.00, z=202.50], EntitySkeleton['Skeleton'/2212, l='MpServer', x=186.50, y=15.00, z=300.50], EntityChicken['Chicken'/2469, l='MpServer', x=253.50, y=45.00, z=203.50], EntityCreeper['Creeper'/2472, l='MpServer', x=217.50, y=53.00, z=286.50], EntitySkeleton['Skeleton'/2219, l='MpServer', x=176.50, y=19.00, z=251.50], EntityCreeper['Creeper'/2736, l='MpServer', x=271.78, y=15.00, z=276.57], EntitySkeleton['Skeleton'/2748, l='MpServer', x=249.50, y=46.00, z=213.50], EntitySkeleton['Skeleton'/2242, l='MpServer', x=220.50, y=57.00, z=316.50], EntityZombie['Zombie'/2754, l='MpServer', x=205.50, y=67.00, z=281.50], EntityZombie['Zombie'/2757, l='MpServer', x=193.20, y=51.00, z=304.48], EntityBat['Bat'/1994, l='MpServer', x=171.01, y=14.16, z=215.13], EntitySkeleton['Skeleton'/2506, l='MpServer', x=155.70, y=24.24, z=225.01], EntitySkeleton['Skeleton'/2762, l='MpServer', x=190.50, y=58.00, z=296.70], EntitySkeleton['Skeleton'/2763, l='MpServer', x=190.50, y=58.00, z=296.08], EntityBat['Bat'/2767, l='MpServer', x=149.99, y=55.28, z=257.40], EntityItem['item.item.seeds'/2515, l='MpServer', x=266.51, y=63.00, z=231.72], EntityBat['Bat'/2771, l='MpServer', x=147.07, y=32.82, z=245.88], EntityItem['item.item.seeds'/2516, l='MpServer', x=267.28, y=63.00, z=231.75], EntityBat['Bat'/2773, l='MpServer', x=148.55, y=32.40, z=245.17], EntityBat['Bat'/2774, l='MpServer', x=146.97, y=32.76, z=244.66], EntityItem['item.item.seeds'/2519, l='MpServer', x=263.13, y=64.00, z=198.83], EntityCreeper['Creeper'/2782, l='MpServer', x=260.50, y=30.00, z=302.50], EntityZombie['Zombie'/2783, l='MpServer', x=260.50, y=30.00, z=300.50], EntityItem['item.tile.mushroom'/2535, l='MpServer', x=248.30, y=66.00, z=195.10], EntityItem['item.item.porkchopRaw'/2539, l='MpServer', x=218.97, y=63.00, z=248.79], EntityXPOrb['Experience Orb'/2541, l='MpServer', x=218.79, y=63.00, z=251.72], EntitySkeleton['Skeleton'/2288, l='MpServer', x=247.50, y=53.00, z=317.50]]
> 	Retry entities: 0 total; []
> 	Server brand: fml,forge
> 	Server type: Integrated singleplayer server
> Stacktrace:
> 	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
> 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_144, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 4108430504 bytes (3918 MB) / 5274861568 bytes (5030 MB) up to 7635730432 bytes (7282 MB)
> 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096M -Xmx8192M -XX:MaxPermSize=128M
> 	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
> 	FML: MCP 9.42 Powered by Forge 14.23.1.2559 Optifine OptiFine_1.12.2_HD_U_C6 7 mods loaded, 7 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State     | ID                 | Version                | Source                            | Signature                                |
> 	|:--------- |:------------------ |:---------------------- |:--------------------------------- |:---------------------------------------- |
> 	| UCHIJAAAA | minecraft          | 1.12.2                 | minecraft.jar                     | None                                     |
> 	| UCHIJAAAA | mcp                | 9.42                   | minecraft.jar                     | None                                     |
> 	| UCHIJAAAA | FML                | 8.0.99.99              | forge-1.12.2-14.23.1.2559.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAAAA | forge              | 14.23.1.2559           | forge-1.12.2-14.23.1.2559.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAAAA | mantle             | 1.12-1.3.1.21          | [CS]-Mantle-1.3.1.21.jar          | None                                     |
> 	| UCHIJAAAA | tconstruct         | 1.12-2.8.0.45          | [T]-TinkersConstruct-2.8.0.45.jar | None                                     |
> 	| UCHIJAAAA | tinkertoolleveling | 1.12-1.0.3.DEV.56fac4f | [T]-TinkerToolLeveling-1.0.3.jar  | None                                     |
> 
> 	Loaded coremods (and transformers): 
> 	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 387.92' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
> 	Pulsar/tconstruct loaded Pulses: 
> 		- TinkerCommons (Enabled/Forced)
> 		- TinkerTools (Enabled/Not Forced)
> 		- TinkerHarvestTools (Enabled/Forced)
> 		- TinkerMeleeWeapons (Enabled/Forced)
> 		- TinkerRangedWeapons (Enabled/Forced)
> 		- TinkerModifiers (Enabled/Forced)
> 		- TinkerSmeltery (Enabled/Not Forced)
> 		- TinkerOredict (Enabled/Forced)
> 		- TinkerIntegration (Enabled/Forced)
> 		- TinkerFluids (Enabled/Forced)
> 		- TinkerMaterials (Enabled/Forced)
> 		- TinkerModelRegister (Enabled/Forced)
> 
> 	Launched Version: 1.12.2
> 	LWJGL: 2.9.4
> 	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 387.92, NVIDIA Corporation
> 	GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 	Type: Client (map_client.txt)
> 	Resource Packs: PureBDCraft-128.zip
> 	Current Language: English (US)
> 	Profiler Position: N/A (disabled)
> 	CPU: 16x AMD Ryzen 7 1700 Eight-Core Processor

**Comment by D3nnis3n** [comment]
I can do one of the complete modpack too, if you wish.

**Comment by D3nnis3n** [comment]
And a question: With hitting do you mean Shooting them with the arrows or just using it like a sword?

**Comment by bonii-xx** [comment]
The crashlog should also contain the full startup log, if you can also post that. And I see you're using forge 2559, can you try if it also happens with 2552?

**Comment by D3nnis3n** [comment]
I think you want this: https://gist.github.com/D3nnis3n/e64d867ae3030aa7510785d3e4094fe4
Yes, happens with 2552 too.

**Comment by bonii-xx** [comment]
You have other mods in there, and it seems to be missing stuff.
Usually the latest.log is fine

**Comment by D3nnis3n** [comment]
This ist the fml-client-latest.log and no, there are no other mods despite optifine active. latest.log is only 1kb with nothin interesting in it, do you need it?

What is missing?

**Comment by bonii-xx** [comment]
Optifine IS another mod. Even worse, a coremod.
And it's missing everything past preInit. Which is about 2/3 of the steps required to start.

**Comment by D3nnis3n** [comment]
Sorry, i cannot remove Optifine - i Need it to scale down the Resolution to Full HD from my 4K Monitor, otherwise graphics will Crash on Startup. Without optifine this is not possible.

The log is everything that got logged in the respective file, nothing is missing from the log. If the log is not complete, i do not know why.

**Comment by D3nnis3n** [comment]
I found a fml-early-junk-Startup log, maybe this one is what you search for or is missing?
https://gist.github.com/D3nnis3n/2d6c77931cb8dda06a8c72688325524a

**Comment by bonii-xx** [comment]
While this has all the stages, it's a different kind of output, not the one I'd need.
If you can't reproduce it with a fresh instance (No previous world. No previous configs) without any additional mods it's pretty much useless to me, since I can't rule out that it's those mods causing it. It works otherwise, after all.

**Comment by D3nnis3n** [comment]
Kay, seems like no fix for me. I can't disable Optifine as i told, game does not work otherwise. :(
Thank you anyway.

**Comment by Th232** [comment]
It would be great if this could be resolved. Arrows do level. and if i mele then so do bows.. but who would mele a bow?
Should level when fired with arrows

**Comment by bonii-xx** [comment]
Congratulations on completely missing the point of the issue, @Th232.
@D3nnis3n maybe somebody else with the issue will come around, and I can reproduce it then. If it isn't another mods fault.

**Comment by D3nnis3n** [comment]
I hope so.

**Comment by Th232** [comment]
Happens

**Comment by richraid21** [comment]
Leveling on ranged weapons works fine on latest 12.2 for me but it is broken in FTB Beyond. 

So do with that information what you'd like

**Comment by bonii-xx** [comment]
Because FTB beyond is a 1.10 pack....?

**Comment by huang-junwei** [comment]
1 question: are you using the latest tinkers tools leveling mod with the latest tinkers tool leveling bolts/arrows (the bolt and arrow with levels)?

**Comment by bonii-xx** [comment]
Cleanup.
