### ISSUE TITLE
Does not work on crossbow if kill by shooting

### ISSUE THREAD

**Issue by huang-junwei** [SlimeKnights/TinkersToolLeveling#55]
If I kill mobs by shooting with crossbow, the crossbow does not gain any experience
here is the crash report by holding f3 + C for 10 seconds:

[crash-2017-12-23_18.56.05-client.txt](https://github.com/SlimeKnights/TinkersToolLeveling/files/1584036/crash-2017-12-23_18.56.05-client.txt)

**Comment by bonii-xx** [comment]
Crossbows gain xp on hit, not on death. Weapons/Arrows gain xp on death. Are you in creative mode?

**Comment by huang-junwei** [comment]
Yes I am in creative

**Comment by huang-junwei** [comment]
The experience stayed at 0 no matter hit or kill

**Comment by bonii-xx** [comment]
Go into survival.

**Comment by huang-junwei** [comment]
Ok, it worked, and I figured out why it doesn't work in my main world.: I forgot to change the old tinkers bolt into the new bolt that have levels.
