### ISSUE TITLE
Not working together with Mending Moss

### ISSUE THREAD

**Issue by NoiZeBeAsT** [SlimeKnights/TinkersToolLeveling#56]
I put a Mending Moss on my Hattock (Certus Quartz/Living Wood/Living Wood) and noticed, that it does not work.

I think the xp buffer for the level ups replaces the one for the mending moss maybe?!

**Comment by bonii-xx** [comment]
XP drops has absolutely nothing to do with tool leveling, and TiC adds neither certus quartz nor living wood. You need to hold the mattock in the hand while picking up xp.
