### ISSUE TITLE
Leveling on any tool doesn't work

### ISSUE THREAD

**Issue by weryus** [SlimeKnights/TinkersToolLeveling#57]
Tools don't level up at all even after surpassing the amount of xp needed
Can't even level up tools with the /leveluptool

Forge Version 14.23.1.2605
TConstruct and Tinkers Tool Leveling are at the latest version
I only have TConstruct and Tinkers Tool leveling installed

**Comment by bonii-xx** [comment]
Mod Versions and screenshot please

**Comment by weryus** [comment]
http://prntscr.com/i77wxd
https://gfycat.com/ChubbyElasticAlabamamapturtle

**Comment by bonii-xx** [comment]
The tool in your gif has no xp, hence it can't level up. Craft a new one.

**Comment by weryus** [comment]
i fixed the problem, I just had to delete and re-make the config file for tinkers tool leveling
