### ISSUE TITLE
[0.2.0] Achieving negative xp with /levelupTool

### ISSUE THREAD

**Issue by SPMoo66** [SlimeKnights/TinkersToolLeveling#6]
Once you reach int (2147483647) as an XP requirement for the next level up (I achieved this using /levelupTool), if you have any XP gained (like 6 / 2147483647), when using /levelupTool once more, it results in a negative XP value appearing, and the tool does not level up. Using /levelupTool again puts you at a positive value again. If you have 0 / 2147483647, you level up normally. I'm assuming this is caused by extra XP being carried over to the next level when using /levelupTool.

Here's an image showing the negative xp-
https://u.pomf.is/jyqjcw.png

I realize this is an extreme edge case and will nearly never be seen, but I figured I'd report it anyway.

**Comment by bonii-xx** [comment]
Well, if you manage to mine blocks for 3 1/2 years continuously at max mining speed... I guess? Not to mention the buildup until you actually require that amount of xp. ;P
