### ISSUE TITLE
Custom level name

### ISSUE THREAD

**Issue by fmohican** [SlimeKnights/TinkersToolLeveling#60]
Can you make an editable level name?
or should i repack zip with custom .lang files?

**Comment by bonii-xx** [comment]
You make a resource pack containing the .lang file.

**Comment by fmohican** [comment]
@bonii-xx can u show me an example?

**Comment by bonii-xx** [comment]
I don't have an existing example, but it works like any resource in a resource pack. Google can help for sure: https://www.google.at/search?q=minecrfat+lang+files+in+resource+packs&oq=minecrfat+lang+files+in+resource+packs&aqs=chrome..69i57.4986j0j7&sourceid=chrome&ie=UTF-8
