### ISSUE TITLE
[FeatureRequest] First tool level-up grants a higher tier of mining 

### ISSUE THREAD

**Issue by Xenooooon** [SlimeKnights/TinkersToolLeveling#61]
I believe it was the Iguana Tweaks mod that allowed this,
Basically
if an stone pick is on level 1 (freshy crafted) and it leveled to level 2 its mining level would now be iron now. it would stay iron on level 3,4,5,6... etc. just the first level up increases the level!

I absolutely loved this feature in Iguana tweaks and would love to see this ported! it was soooooo amazing for progression!

**Comment by bonii-xx** [comment]
Not in the scope of TTL. I've deliberately kept the scope of this mod to purely leveling and adding free modifiers.
