### ISSUE TITLE
Server Crashes on Starting

### ISSUE THREAD

**Issue by TRUEBLUD** [SlimeKnights/TinkersToolLeveling#62]
https://pastebin.com/C7JxFfAR (fml-server-latest)
https://pastebin.com/Ugkfd0MA (Crash report)

I don't know if i'm just an idiot and glossed over something while reading about the mod or there is a incompatibility with the new forge. just trying to make a server for fun with friends and really wanted this mod to work it's one of the few that didn't work when i popped it in so hoping for a fix. i have run this by itself without other mod installed.

**Comment by KnightMiner** [comment]
Your logs appear incomplete, thought the error is still visible. This mod depends on both Mantle and Tinkers Construct, ensure you have the latest versions of each for your version of Minecraft.

**Comment by bonii-xx** [comment]
Closed due to no response.
