### ISSUE TITLE
Veinminer not compatable

### ISSUE THREAD

**Issue by 21Ryno21** [SlimeKnights/TinkersToolLeveling#64]
In 1.12.2 using veinminer doesn't give you xp towards your tool. i.e. veinmining stone with tinkers pickaxe. Is there anyway to solve this so you get the full xp for the blocks you mined?

**Comment by bonii-xx** [comment]
Veinminer probably doesn't use the tool to break the blocks, xp works off of the callbacks called by MC/Forge. However if you use tool leveling and veinminer together, you're probably better off just using creative modifiers.
