### ISSUE TITLE
Items Not Have XP Indicator

### ISSUE THREAD

**Issue by DarkThanatos** [SlimeKnights/TinkersToolLeveling#68]
Hi..well when me craft any tool in our server (1.12.2) shows Clumsy level in item, but if you put in inventory not showing XP indicator and  level of tool.

example:

Crafting and shows all info
![2018-05-08_22 40 22](https://user-images.githubusercontent.com/21208365/39792892-4ac5b16a-5319-11e8-8181-e42e7bb01f4e.png)

But If i put in inventory
![2018-05-08_22 40 30](https://user-images.githubusercontent.com/21208365/39792912-645310be-5319-11e8-9e7d-c4b1d11b75bc.png)

how i can solve this issue?

Best Regards.

**Comment by bonii-xx** [comment]
Probably some other mod interfering. Try reproducing with only TiC and tool leveling.

**Comment by bonii-xx** [comment]
Cleanup, closing old tickets.
