### ISSUE TITLE
[0.2.0] Base XP config values for excavator, hammer, and lumberaxe resetting

### ISSUE THREAD

**Issue by SPMoo66** [SlimeKnights/TinkersToolLeveling#7]
Despite the fix, my config values for excavator, hammer, and lumberaxe keep resetting to 4500. I tried setting every tool at a base XP value of 1, then loading MC, and this is what the config file changed to-

http://pastebin.com/8At6W0Pn

**Comment by bonii-xx** [comment]
Thanks, fixed next release.
