### ISSUE TITLE
{ Proposal, Request } Change to version 1.7.10

### ISSUE THREAD

**Issue by DarkSnipep** [SlimeKnights/TinkersToolLeveling#72]
Hello, I'm in no programming and creating mods with addons I do not know how to do them at all, but I would like to ask you to change this divine modification for "Tinkers' Construct" to version 1.7.10
(Well, for others, lower or higher versions from 1.7.10)

**Comment by Ravin890** [comment]
Iguana tinkers tweaks

**Comment by DarkSnipep** [comment]
Thank you, for writing about "Iguana tinkers tweaks"
