### ISSUE TITLE
Crash on Initialize

### ISSUE THREAD

**Issue by Dragnier** [SlimeKnights/TinkersToolLeveling#75]
Crashlog: https://paste.dimdev.org/obavinatut.mccrash

**Comment by bonii-xx** [comment]
You got some coremod breaking your game, not a TTL issue.

**Comment by Dragnier** [comment]
@bonii-xx Any idea which? At least where I might start looking (disabling) to find it and report to the correct author?

**Comment by KnightMiner** [comment]
Its really difficult to tell, some mod caused the proxy to no longer load, which is a core Forge feature that is not implemented differently in TTL. Your best bet is just removing all core mods first to see if that fixes it. If not, try them half at a time and keep halving until you find the culprit.
