### ISSUE TITLE
Leveling speed question

### ISSUE THREAD

**Issue by garfu** [SlimeKnights/TinkersToolLeveling#80]
Why not implement an xp speed factor into the config? I play singleplayer and would like my tools to level slightly faster. I had to recompile your mod with a faster xp rate... so I figured maybe there were others out there that would want that as well.

**Comment by bonii-xx** [comment]
Because they're set to soft cap relatively quickly after a few modifiers. If you need more, switch to creative modifiers from TiC.

**Comment by garfu** [comment]
Makes sense, thanks for the response. Also I'm dumb and didn't realize at first that lowering the starting xp is essentially the way to change xp gain factor...
