### ISSUE TITLE
Suggestion: Configurable Multiplier

### ISSUE THREAD

**Issue by Kinkypie** [SlimeKnights/TinkersToolLeveling#83]
The original Iguana Tinker Tweaks, as well as the leveling portion of the Contruct's Armory mod, include an option in their configs to change the amount of xp required for each level exponentially. Adding this option to Tinker's tool Leveling would keep it in line with the expected behavior of other similar mods as well as make it so those folks who "just want creative modifiers" can get each level a little easier while still setting the game up to require a moderate effort every level without the grind becoming nigh impossible after a few levels.

**Comment by bonii-xx** [comment]
This has been on here so often already. No the multiplier is intended to act as a soft cap. If you want creative modifiers, use creative modifiers. That's what they're there for.
